name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
        
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v3
       
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
         
     - name: Terraform Init
       run: |
          terraform init \
            -backend-config="bucket=hcl-test-backend-state" \
            -backend-config="key=usecase2//to/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="encrypt=true" 
        
     - name: Terraform destroy
       id: destroy
       run: terraform destroy -auto-approve
